version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31119
functions:
  mr-compose-and-upload:
    lang: python3-flask
    handler: ./mr-compose-and-upload
    image: mr-compose-and-upload:latest
    labels:
      "com.openfaas.scale.max": "1" 
      "com.openfaas.scale.min": "1" 
    constraints:
     - "kubernetes.io/hostname=kube-node-7"
